controllers/UserController.php
<?php

class UserController extends BoxomaticController
{

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column1';

    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class'     => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
        );
    }

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('passwordReset', 'forgottenPassword', 'captcha'),
                'users'   => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('update', 'view', 'loginAs', 'changePassword', 'dontWant', 'createLocation'),
                'roles'   => array('customer', 'Admin'),
            //'users'=>array('*'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('index', 'admin', 'delete', 'create', 'customers', 'resetPassword', 'export'),
                'roles'   => array('Admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $model = $this->loadModel($id);
        if (!Yii::app()->user->checkAccess('Admin') && $model->id != Yii::app()->user->id)
        {
            throw new CHttpException(403, 'Access Denied.');
        }
        $this->render('view', array(
            'model' => $model,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new BoxomaticUser;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['BoxomaticUser']))
        {
            $model->scenario = 'changePassword';
            $model->attributes = $_POST['BoxomaticUser'];
            //if (isset($_POST['BoxomaticUser']['password']))
                //$model->password = $_POST['BoxomaticUser']['password'];
            if ($model->save())
            {
                if (isset($_POST['role'])) {
                    $model->setRole($_POST['role']);
                }
                if (isset($_POST['role']) && $_POST['role'] == 'customer')
                {
                    if (empty($model->user_id)) {
                        $Customer = new Customer();
                    } else {
                        $Customer = Customer::model()->findByPk($model->user_id);
                    }
                    $Customer->attributes = $_POST['Customer'];
                    $Customer->save();

                    if (!$Customer->Location->is_pickup)
                    {
                        $UserLoc = new UserLocation;
                        $UserLoc->user_id = $Customer->id;
                        $UserLoc->location_id = $Customer->location_id;
                        $UserLoc->address = $Customer->user_address;
                        $UserLoc->address2 = $Customer->user_address2;
                        $UserLoc->suburb = $Customer->user_suburb;
                        $UserLoc->state = $Customer->user_state;
                        $UserLoc->postcode = $Customer->user_postcode;
                        $UserLoc->phone = !empty($Customer->user_phone) ? $Customer->user_phone : $Customer->user_mobile;
                        $UserLoc->save(false);
                        $Customer->user_location_id = $UserLoc->customer_location_id;
                    }

                    $model->user_id = $Customer->user_id;
                    $model->update(array('user_id'));
                }

                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $model->password = null;
        $model->password_repeat = null;
        
        $custLocDataProvider = false;

        $this->render('create', array(
            'model'               => $model,
            'custLocDataProvider' => $custLocDataProvider
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $Customer = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['BoxomaticUser']))
        {
            $oldLocation = $Customer->location_id;
            $oldDeliveryDay = $Customer->delivery_day;
            $allSaved = false;
            
            $Customer->attributes = $_POST['BoxomaticUser'];

            $locationId = $_POST['BoxomaticUser']['delivery_location_key'];
            $custLocationId = null;
            if (strpos($locationId, '-'))
            { //has a customer location
                $parts = explode('-', $locationId);
                $locationId = $parts[1];
                $custLocationId = $parts[0];
            }
            $Customer->location_id = $locationId;
            $Customer->user_location_id = $custLocationId;

            if ($Customer->validate())
                $Customer->update();
            else
                $allSaved = false;
            
            //The frontend system currently doesn't handle ordering from multiple locations
            //so delete all orders if changing location
            if($Customer->location_id != $oldLocation || $Customer->delivery_day != $oldDeliveryDay) 
            {
                $deleted = false;
                foreach($Customer->getFutureOrders() as $Order) {
                    $Order->delete();
                    $deleted = true;
                }
                Yii::import('frontend.components.BoxoCart');
                $BoxoCart = new BoxoCart();
                $BoxoCart->emptyCart();
                if($deleted) {
                    Yii::app()->user->setFlash('warning', 'All future orders removed.');
                }
            }

            if ($allSaved)
                $this->redirect(array('user/update', 'id' => $Customer->id));
        }

        $allSaved = true;
        /*
          if(isset($_POST['Customer']))
          {
          $Customer=$model->Customer;
          $locationId=$_POST['Customer']['delivery_location_key'];
          $custLocationId=new CDbExpression('NULL');
          if(strpos($locationId,'-'))
          { //has a customer location
          $parts=explode('-',$locationId);
          $locationId=$parts[1];
          $custLocationId=$parts[0];
          }

          $Customer->location_id=$locationId;
          $Customer->customer_location_id=$custLocationId;
          $Customer->save();

          $Customer->attributes=$_POST['Customer'];
          if(!$Customer->update())
          $allSaved=false;

          $Customer->updateOrderDeliveryLocations();
          }
         */

        if (isset($_POST['Supplier']))
        {
            $Supplier = $Customer->Supplier;
            $Supplier->attributes = $_POST['Supplier'];
            if (!$Supplier->update())
                $allSaved = false;
        }

        if (isset($_POST['role']))
        {
            $Customer->setRole($_POST['role']);
        }

        /*
        if (isset($_POST['BoxomaticUser']))
        {
            $model->attributes = $_POST['BoxomaticUser'];
            $model->validate();
            if (!$model->update())
                $allSaved = false;

            if ($allSaved)
                $this->redirect(array('customers'));
        }
         */

        $custLocDataProvider = null;
        $custLocDataProvider = new CActiveDataProvider('UserLocation', array(
            'criteria' => array(
                'condition' => 'user_id=' . $Customer->id
            )
        ));

        $this->render('update', array(
            'model'               => $Customer,
            'custLocDataProvider' => $custLocDataProvider
        ));
    }

    /**
     * Change password page
     * @param integer $id the ID of the model to be updated
     */
    public function actionChangePassword($id)
    {
        $model = $this->loadModel($id);
        $model->scenario = 'changePassword';
        if (isset($_POST['BoxomaticUser']))
        {
            $model->attributes = $_POST['BoxomaticUser'];
            if ($model->validate())
            {
                $model->update();
                Yii::app()->user->setFlash('success', "Password updated.");
                $this->redirect(array('view', 'id' => $model->id));
            }
        }
        $this->render('changePassword', array(
            'model' => $model,
        ));
    }

    /**
     * Csv Export
     */
    public function actionExport()
    {
        CsvExport::export(
                User::model()->findAll(), // a CActiveRecord array OR any CModel array
                array(
            'id'              => array('number'),

views/user/_form.php
<?php
/**
 * @var $model BoxomaticUser
 * @var $form SnapActiveForm
 * @var $this UserController
 * @var $custLocDataProvider CActiveDataProvider
 */
$baseUrl = $this->createFrontendUrl('/').'/themes/boxomatic/admin';
$cs = Yii::app()->clientScript;
$cs->registerScriptFile($baseUrl . '/js/vendor/tag-it.min.js', CClientScript::POS_END);
$cs->registerCssFile($baseUrl . '/css/jquery.tagit.css');
$cs->registerCssFile($baseUrl . '/css/tagit.ui-zendesk.css');
?>
    <script type="text/javascript">
        var availableTags = <?php echo json_encode(array_values(Tag::getList())) ?>;
    </script>
    <div class="form">
        <?php $form = $this->beginWidget('application.widgets.SnapActiveForm', array(
            'id' => 'user-form',
            'enableAjaxValidation' => false,
            'layout' => BsHtml::FORM_LAYOUT_HORIZONTAL,
            'htmlOptions' => array('class' => 'row'),
        )); ?>
        <div class="col-lg-9 clearfix">
			<?php if ($form->errorSummary($model)): ?>
            <div data-alert class="alert-box alert">
                <?php echo $form->errorSummary($model); ?>
                <a href="#" class="close">&times;</a>
            </div>
			<?php endif; ?>

            <?php echo $form->textFieldControlGroup($model, 'first_name', array('size' => 45, 'maxlength' => 45)); ?>
            <?php echo $form->textFieldControlGroup($model, 'last_name', array('size' => 45, 'maxlength' => 45)); ?>
            <?php echo $form->textFieldControlGroup($model, 'email', array('size' => 255, 'maxlength' => 255)); ?>

            <?php if ($model->isNewRecord): ?>
                <?php echo $form->passwordFieldControlGroup($model, 'password', array('size' => 255, 'maxlength' => 255)); ?>
                <?php echo $form->passwordFieldControlGroup($model, 'password_repeat', array('size' => 255, 'maxlength' => 255)); ?>
            <?php endif; ?>

            <?php echo $form->textFieldControlGroup($model, 'user_phone', array('size' => 45, 'maxlength' => 45)); ?>
            <?php echo $form->textFieldControlGroup($model, 'user_mobile', array('size' => 45, 'maxlength' => 45)); ?>
            <?php echo $form->textFieldControlGroup($model, 'user_suburb'); ?>
            <?php echo $form->textFieldControlGroup($model, 'user_address'); ?>
            <?php echo $form->dropDownListControlGroup($model, 'user_state', SnapUtil::config('boxomatic/states')); ?>
            <?php echo $form->textFieldControlGroup($model, 'user_postcode', array('size' => 45, 'maxlength' => 45)); ?>
            <?php echo $form->textAreaControlGroup($model, 'notes'); ?>
			<?php echo $form->checkBoxControlGroup($model, 'reminder_messages'); ?>

            <!--
		<div class="form-group">
			<?php echo $form->label($model, 'tags', array('class' => 'control-label col-lg-2')); ?>
			<div class="col-lg-10">
				<?php echo $form->hiddenField($model, 'tag_names'); ?>
			</div>
		</div>
                -->

            <?php if (Yii::app()->user->checkAccess('Admin')): ?>
                <?php echo BsHtml::dropDownListControlGroup('role', $model->getRole(), CHtml::listData(Yii::app()->authManager->getRoles(), 'name', 'name'), array(
                    'formLayout' => $form->layout,
                    'label' => 'Role',
                )) ?>


                <fieldset>
                    <legend>Delivery Addresses</legend>

                    <?php if ($model->isNewRecord): ?>
                        <?php echo $form->dropDownListControlGroup($model, 'location_id', Location::getDeliveryAndPickupList(), array(
                            'prompt' => '- Select -'
                        )) ?>
                    <?php else: ?>
                        <?php echo $form->dropDownListControlGroup($model, 'delivery_location_key', $model->getDeliveryLocations(), array(
                            'help' => 'Changing this will update all your order locations',
                        )); ?>
                    <?php endif; ?>

                    <?php if ($custLocDataProvider): ?>
                        <div class="row">
                            <div class="col-md-offset-2 col-md-10">
                                <p><?php echo CHtml::link('Add a location', array('userLocation/create', 'custId' => $model->id), array('class' => 'btn btn-sm btn-primary')); ?></p>

                                <div class="row">
                                    <?php $this->widget('bootstrap.widgets.BsListView', array(
                                        'dataProvider' => $custLocDataProvider,
                                        'summaryText' => '',
                                        'itemView' => '../userLocation/_view',
                                        'id' => 'delivery-locations'
                                    )); ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </fieldset>


                <?php if ($model->Supplier): $Supplier = $model->Supplier; ?>

                    <fieldset>
                        <legend>Supplier Details</legend>
                        <div class="large-12 columns">
                            <?php echo $form->labelEx($Supplier, 'website'); ?>
                            <?php echo $form->textField($Supplier, 'website', array('size' => 60, 'maxlength' => 100)); ?>
                            <?php echo $form->error($Supplier, 'website'); ?>
                        </div>

                        <div class="large-12 columns">
                            <?php echo $form->labelEx($Supplier, 'distance_kms'); ?>
                            <?php echo $form->textField($Supplier, 'distance_kms', array('size' => 45, 'maxlength' => 45)); ?>
                            <?php echo $form->error($Supplier, 'distance_kms'); ?>
                        </div>

                        <div class="large-4 columns">
                            <?php echo $form->labelEx($Supplier, 'bank_account_name'); ?>
                            <?php echo $form->textField($Supplier, 'bank_account_name', array('size' => 45, 'maxlength' => 45)); ?>
                            <?php echo $form->error($Supplier, 'bank_account_name'); ?>
                        </div>
                        <div class="large-4 columns">
                            <?php echo $form->labelEx($Supplier, 'bank_bsb'); ?>
                            <?php echo $form->textField($Supplier, 'bank_bsb', array('size' => 45, 'maxlength' => 45)); ?>
                            <?php echo $form->error($Supplier, 'bank_bsb'); ?>
                        </div>
                        <div class="large-4 columns">
                            <?php echo $form->labelEx($Supplier, 'bank_acc'); ?>
                            <?php echo $form->textField($Supplier, 'bank_acc', array('size' => 45, 'maxlength' => 45)); ?>
                            <?php echo $form->error($Supplier, 'bank_acc'); ?>
                        </div>
                        <div class="large-6 columns">
                            <?php echo $form->labelEx($Supplier, 'certification_status'); ?>
                            <?php echo $form->textField($Supplier, 'certification_status', array('size' => 60, 'maxlength' => 150)); ?>
                            <?php echo $form->error($Supplier, 'certification_status'); ?>
                        </div>
                        <div class="large-6 columns">
                            <?php echo $form->labelEx($Supplier, 'order_days'); ?>
                            <?php echo $form->textField($Supplier, 'order_days', array('size' => 60, 'maxlength' => 255)); ?>
                            <?php echo $form->error($Supplier, 'order_days'); ?>
                        </div>
                        <div class="large-12 column">
                            <?php echo $form->labelEx($Supplier, 'produce'); ?>
                            <?php echo $form->textArea($Supplier, 'produce', array('rows' => 6, 'cols' => 50)); ?>
                            <?php echo $form->error($Supplier, 'produce'); ?>
                        </div>
                        <div class="large-12 columns">
                            <?php echo $form->labelEx($Supplier, 'notes'); ?>
                            <?php echo $form->textArea($Supplier, 'notes', array('rows' => 6, 'cols' => 50)); ?>
                            <?php echo $form->error($Supplier, 'notes'); ?>
                        </div>
                        <div class="large-12 columns">
                            <?php echo $form->labelEx($Supplier, 'payment_details'); ?>
                            <?php echo $form->textArea($Supplier, 'payment_details', array('rows' => 6, 'cols' => 50)); ?>
                            <?php echo $form->error($Supplier, 'payment_details'); ?>
                        </div>
                    </fieldset>

                <?php endif; ?>

            <?php endif; ?>
        </div>
        <div id="sidebar" class="col-lg-3">
            <?php $this->beginWidget('bootstrap.widgets.BsPanel', array(
                'title' => 'Menu',
                'contentCssClass' => '',
                'htmlOptions' => array(
                    'class' => 'panel sticky',
                ),
                'type' => BsHtml::PANEL_TYPE_PRIMARY,
            )); ?>
            <div class="btn-group btn-group-vertical">
                <?php echo BsHtml::submitButton(BsHtml::icon(BsHtml::GLYPHICON_THUMBS_UP) . ' Save'); ?>

                <?php $this->widget('application.widgets.SnapMenu', array(
                    'items' => $this->menu,
                    'htmlOptions' => array('class' => 'nav nav-stacked'),
                )); ?>
            </div>
            <?php $this->endWidget(); ?>
        </div>
    </div>

<?php $this->endWidget(); ?>

views/user/_search.php
<div class="wide form">
<?php $form=$this->beginWidget('bootstrap.widgets.BsActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
	'layout' => BsHtml::FORM_LAYOUT_HORIZONTAL,
	'htmlOptions' => array('class'=>'row')
)); ?>
	<fieldset class="col-md-12">
		<?php echo $form->textFieldControlGroup($model,'first_name'); ?>
		<?php echo $form->textFieldControlGroup($model,'last_name'); ?>
		<?php echo $form->textFieldControlGroup($model,'email'); ?>
		<?php echo $form->textFieldControlGroup($model,'user_phone'); ?>
		<?php echo $form->textFieldControlGroup($model,'user_mobile'); ?>
		<?php echo $form->textFieldControlGroup($model,'user_address'); ?>
		<?php echo $form->textFieldControlGroup($model,'user_suburb'); ?>
		<?php echo $form->textFieldControlGroup($model,'user_state'); ?>
		<?php echo $form->textFieldControlGroup($model,'user_postcode'); ?>
		<?php echo $form->textAreaControlGroup($model,'search_customer_notes'); ?>
	</fieldset>
		
	<div class="form-actions col-md-offset-2 col-md-10">
		<?php echo BsHtml::submitButton(BsHtml::icon(BsHtml::GLYPHICON_SEARCH).' Search', array('color' => BsHtml::BUTTON_COLOR_PRIMARY)); ?>
	</div>
<?php $this->endWidget(); ?>
</div>

views/user/admin.php
<?php
$this->breadcrumbs=array(
	'Box-O-Matic'=>array('/snapcms/boxomatic/index'),
	'Delivery Dates',
);
$this->page_heading = 'Customers';

Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('user-grid', {
		data: $(this).serialize()
	});
	return false;
});
");

$this->menu = array(
	//array('icon' => 'glyphicon-plus-sign','label'=>'Create Customer', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$Content->id),'confirm'=>'Are you sure you want to delete this item?')),
);

Yii::app()->clientScript->registerScript('initPageSize',<<<EOD
	$('#content').on('change', '.change-pageSize', function() {
		$.fn.yiiGridView.update('user-grid',{ data:{ pageSize: $(this).val() }})
	});
EOD
,CClientScript::POS_READY);
?>

<div class="row">
	<div class="large-12 columns">
		<h1>Manage Users</h1>
	</div>

	<div class="large-12 columns">
		<div class="panel">
			<?php echo CHtml::link('Create User',array('user/create'),array('class'=>'button small')) ?>
			<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button button small')); ?>
		</div>
	</div>

	<div class="large 12 columns search-form" style='display:none'>
		<?php $this->renderPartial('_search',array(
			'model'=>$model,
		)); ?>
	</div>

	<div class="large-12 columns">
		
		<?php $dataProvider=$model->search(); ?>
		<?php $pageSize=Yii::app()->user->getState('pageSize',10); ?>
		<?php $this->widget('bootstrap.widgets.BsGridView', array(
			'id'=>'user-grid',
			'cssFile' => '', 
			'dataProvider'=>$dataProvider,
			'summaryText'=>'Displaying {start}-{end} of {count} result(s). ' .
			CHtml::dropDownList(
				'pageSize',
				$pageSize,
				array(5=>5,10=>10,20=>20,50=>50,100=>100),
				array('class'=>'change-pageSize')) .
			' rows per page',
			'filter'=>$model,
			'columns'=>array(
				'id',
				'first_name',
				'last_name',
				'email',
				array(
					'name'=>'Customer.balance',
					'value'=>'$data->Customer ? SnapFormat::currency($data->Customer->balance) : ""',
				),
				'last_login_time',
				array( 'name'=>'user_id', 'value'=>'empty($data->user_id) ? "No" : "Yes"'),
				array( 'name'=>'supplier_id', 'value'=>'empty($data->supplier_id) ? "No" : "Yes"'),
				array(
					'class'=>'bootstrap.widgets.BsButtonColumn',
					'template'=>'{view}{update}{delete}{login}',
					'buttons'=>array(
						'login' => array
						(
							'label'=>'<i class="fi fi-key"></i>',
							'url'=> 'array("user/loginAs","id"=>$data->id)',
							'options'=>array('title'=>'Login As'),
						),
					),
				),
			),
		)); ?>
	</div>
</div>

views/user/changePassword.php
<div class="row">
	<div class="large-12 columns">
		<h1><?php echo $model->full_name; ?></h1>
	</div>

	<?php $form=$this->beginWidget('application.widgets.SnapActiveForm', array(
		'id'=>'user-form',
		'enableAjaxValidation'=>false, 
		'htmlOptions' => array('class' => 'custom' )
	)); ?>
	
	<div class="large-8 columns">
		<fieldset>
			<legend>Change Password</legend>
			<?php if($form->errorSummary($model)): ?>

			<div class="large-12 columns">
				<div data-alert class="alert-box alert">
				 <?php echo $form->errorSummary($model); ?>
				 <a href="#" class="close">&times;</a>
				</div>
			</div>

			<?php endif; ?>

			<div class="large-6 columns">
				<?php echo $form->labelEx($model,'password'); ?>
				<?php echo $form->passwordField($model,'password',array('size'=>60,'maxlength'=>255,'value'=>'')); ?>
				<?php echo $form->error($model,'password'); ?>
			</div>
			<div class="large-6 columns">
				<?php echo $form->labelEx($model,'password_repeat'); ?>
				<?php echo $form->passwordField($model,'password_repeat',array('size'=>60,'maxlength'=>255,'value'=>'')); ?>
				<?php echo $form->error($model,'password_repeat'); ?>
			</div>
			<div class="large-12 columns">
				<?php echo CHtml::submitButton('Save', array('class' => 'button')); ?>
			</div>
		</fieldset>

	</div>

	<?php $this->endWidget(); ?>

</div>

views/user/customers.php
<?php
$this->breadcrumbs=array(
	'Box-O-Matic'=>array('/snapcms/boxomatic/index'),
	'Customers',
);
$this->page_heading = 'Customers';

Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('user-grid', {
		data: $(this).serialize()
	});
	return false;
});
");

$this->menu = array(
	array('icon' => 'glyphicon glyphicon-plus-sign', 'label'=>'Create Customer', 'url'=>array('user/create')),
	array('icon' => 'glyphicon glyphicon-export', 'label'=>'Export Customers', 'url'=>array('user/export')),
);

Yii::app()->clientScript->registerScript('initPageSize',<<<EOD
	$('#content').on('change', '.change-pageSize', function() {
		$.fn.yiiGridView.update('user-grid',{ data:{ pageSize: $(this).val() }})
	});
EOD
,CClientScript::POS_READY);
?>
<?php
$this->beginWidget('bootstrap.widgets.BsPanel', array(
	'title'=>BsHtml::button('Advanced search',array(
		'data-toggle' => 'collapse',
		'data-target' => '#search-form',
		'class' =>'search-button', 
		'icon' => BsHtml::GLYPHICON_SEARCH,
		'color' => BsHtml::BUTTON_COLOR_PRIMARY), '#'),
)); ?>
	<div id="search-form" class="search-form collapse">
		<?php echo $this->renderPartial('_search',array(
			'model'=>$model,
		)); ?>
	</div><!-- search-form -->
	<?php $dataProvider=$model->search(); ?>
	<?php $pageSize=Yii::app()->user->getState('pageSize',50); ?>
	<?php $this->widget('bootstrap.widgets.BsGridView', array(
		'id'=>'user-grid',
		'cssFile' => '', 
		'dataProvider'=>$dataProvider,
		'summaryText'=>'Displaying {start}-{end} of {count} result(s). ' .
		CHtml::dropDownList(
			'pageSize',
			$pageSize,
			array(5=>5,10=>10,20=>20,50=>50,100=>100),
			array('class'=>'change-pageSize')) .
		' rows per page',
		'filter'=>$model,
		'columns'=>array(
			'id',
			'first_name',
			'last_name',
			'email',
			array(
				'name'=>'balance',
				'value'=>'SnapFormat::currency($data->balance)',
			),
			//'last_login_time',
			//array( 'name'=>'user_id', 'value'=>'empty($data->user_id) ? "No" : "Yes"'),
			//array( 'name'=>'supplier_id', 'value'=>'empty($data->supplier_id) ? "No" : "Yes"'),
			array(
				'name'=>'tag_name_search',
				'filter'=>Tag::getUsedTags('Users'),
				'value'=>'CHtml::value($data,"tag_names")',
			),
			array(
				'class'=>'bootstrap.widgets.BsButtonColumn',
				'template'=>'{view}{update}{delete}{login}{reset_password}',
				'deleteConfirmation'=>'Delete this customer will delete all their payments and locations. Are your sure want to delete this customer?',		
				'buttons'=>array(
					'login' => array
					(
						'label'=>'<i class="glyphicon glyphicon-user"></i>',
						'url'=> 'array("user/loginAs","id"=>$data->id)',
						'options'=>array('title'=>'Login As'),
					),
					'reset_password' => array
					(
						'label'=>'<i class="glyphicon glyphicon-lock"></i>',
						'url'=> 'array("user/resetPassword","id"=>$data->id)',
						'options'=>array(
							'confirm'=>'Are you sure you want to reset this user\'s password and send them a welcome email?',
							'title'=>'Reset Password',
						),
					),
				),
			),
		),
	)); ?>
<?php $this->endWidget(); ?>

views/user/index.php
<div class="row">
	<div class="large-12 columns">
		<h1>Users</h1>
	</div>
	<div class="large-12 columns">
		<div class="panel">
			<?php echo CHtml::link('Create User',array('user/create'),array('class'=>'button small')) ?>
			<?php echo CHtml::link('Manage User',array('user/admin'),array('class'=>'button small')) ?>
		</div>
	</div>
	
	<?php $dataProvider->pagination->pageSize = 9; ?>

	<?php $this->widget('zii.widgets.CListView', array(
		'dataProvider'=>$dataProvider,
		'itemView'=>'_view'
	)); ?>
	
</div>