models/UserBox.php
<?php

/**
 * This is the model class for table "user_boxes".
 *
 * The followings are the available columns in table 'user_boxes':
 * @property integer $user_box_id
 * @property integer $user_id
 * @property integer $box_id
 * @property integer $quantity
 * @property integer $status
 * @property float $price
 * @property-read boolean $statusOptions
 *
 * The followings are the available model relations:
 * @property BoxomaticUser $User
 * @property Box[] $box
 * @property Order $Order
 */
class UserBox extends BoxomaticActiveRecord
{

    const STATUS_NOT_PROCESSED = 0;
    const STATUS_APPROVED = 1;
    const STATUS_DECLINED = 2;
    const STATUS_DELIVERED = 3;
    const STATUS_REFUNDED = 4;

    public $date_total = null;  //holds an aggregate total for the date;
    public $fulfilled_total = null; //holds an aggregate total for all orders before the deadline
    public $customer_full_name;
    public $customer_box_price;
    public $customer_user_id;
    public $customer_extras_price;
    public $search_extras;
    public static $quantityOptions = array(
        '0' => 0,
        '1' => 1,
        '2' => 2,
        '3' => 3,
        '4' => 4,
        '5' => 5,
        '6' => 6,
        '7' => 7,
        '8' => 8,
        '9' => 9,
        '10' => 10
    );

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return UserBox the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return $this->tablePrefix . 'user_boxes';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('user_id, quantity', 'required'),
            array('box_id', 'required', 'message' => 'Please select a box'),
            array('status, user_id, box_id, quantity', 'numerical', 'integerOnly' => true, 'min' => 0),
            array('delivery_cost, price', 'numerical'),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('search_extras, customer_user_id, customer_box_price, customer_full_name, status, user_box_id, user_id, box_id, quantity', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'User' => array(self::BELONGS_TO, 'BoxomaticUser', 'user_id'),
            'Box' => array(self::BELONGS_TO, 'Box', 'box_id'),
            'Order' => array(self::BELONGS_TO, 'Order', 'order_id')
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'user_box_id' => 'Customer Box',
            'user_id' => 'Customer',
            'box_id' => 'Box',
            'quantity' => 'Quantity',
            'status' => 'Status',
            'customer_full_name' => 'Customer',
            'customer_box_price' => 'Box Price',
            'customer_user_id' => 'User ID',
            'price' => 'Price',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('user_box_id', $this->user_box_id);
        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('box_id', $this->box_id);
        $criteria->compare('quantity', $this->quantity);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function boxSearch($date = null)
    {
        $pageSize = isset($_GET['pageSize']) ? $_GET['pageSize'] : 10;
        Yii::app()->user->setState('pageSize', $pageSize);

        $criteria = new CDbCriteria;

        if ($date)
        {
            $criteria->together = true;
            $criteria->with = array(
                'Box' => array(
                    'condition' => 'delivery_date_id=' . $date,
                ),
                'User'
            );
            if ($this->customer_full_name) {
                $criteria->compare('CONCAT(User.first_name,User.last_name)', $this->customer_full_name, true);
            }
            if ($this->customer_box_price) {
                $criteria->compare('Box.box_price', $this->customer_box_price, true);
            }
            if ($this->customer_user_id) {
                $criteria->compare('User.id', $this->customer_user_id, true);
            }
        }

        $criteria->compare('status', $this->status);
        $criteria->compare('user_box_id', $this->user_box_id);
        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('box_id', $this->box_id);
        $criteria->compare('quantity', $this->quantity);

        return new CActiveDataProvider(get_class($this), array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => $pageSize,
            ),
//			'pagination'=>false,
        ));
    }

    public function getTotal_delivery_price()
    {
        $price = false;
        if($this->User) {
            $price = $this->User->Location->location_delivery_value * $this->quantity;
        }
        return $price;
    }

    public function getTotal_box_price()
    {
        $price = $this->Box->box_price * $this->quantity;
        return $price;
    }

    public function getTotal_price()
    {
        $price = ($this->Box->box_price * $this->quantity);
        if($this->User && $this->User->Location) {
            $price += $this->User->Location->location_delivery_value * $this->quantity;
        }
        return $price;
    }

    /*
     * Only allow changes before the delivery deadline if the user is not an admin
     */

    public function beforeSave()
    {
        $DeliveryDate = $this->Box->DeliveryDate;

        if (time() > strtotime($DeliveryDate->deadline) &&
                !Yii::app()->user->checkAccess('Admin') &&
                !isset(Yii::app()->user->shadow_id) &&
                Yii::app()->getAuthManager()->checkAccess('admin', Yii::app()->user->shadow_id))
        {

            return false;
        } else
            return true;
    }

    public static function findUserBox($dateId, $sizeId, $userId)
    {
        $criteria = new CDbCriteria;
        $criteria->with = 'Box';
        $criteria->select = '*, COUNT(user_box_id) as quantity';
        $criteria->addCondition("Box.size_id=$sizeId");
        $criteria->addCondition("Box.delivery_date_id=$dateId");
        $criteria->addCondition("user_id=$userId");
        $box = self::model()->find($criteria);

        //If there's no user_id the box wasn't found. (The aggregate COUNT 
        //function causes an empty row to be found)
        if (!$box || !$box->user_id)
            $box = null;

        return $box;
    }

    public static function random($boxId)
    {
        $criteria = new CDbCriteria;
        $criteria->addCondition("box_id=$boxId");
        $criteria->order = 'RAND()';
        $box = self::model()->find($criteria);
        return $box;
    }

    public function getStatusOptions()
    {
        return array(
            self::STATUS_NOT_PROCESSED => 'Not Processed',
            self::STATUS_APPROVED => 'Approved',
            self::STATUS_DECLINED => 'Declined',
            self::STATUS_DELIVERED => 'Collected/Delivered',
            self::STATUS_REFUNDED => 'Refunded'
        );
    }

    /**
     * @return string the status text display for the current issue
     */
    public function getStatus_text()
    {
        $statusOptions = $this->statusOptions;
        return isset($statusOptions[$this->status]) ? $statusOptions[$this->status] : "unknown status ({$this->status})";
    }

    public function getDelivery_location()
    {
        $CustDeliveryDate = Order::model()->findByAttributes(array(
            'user_id' => $this->user_id,
            'delivery_date_id' => $this->Box->delivery_date_id
        ));
        if ($CustDeliveryDate)
            return $CustDeliveryDate->delivery_location;
        else
            return 'No location set!';
    }

    public function getDelivery_address()
    {
        $CustDeliveryDate = Order::model()->findByAttributes(array(
            'user_id' => $this->user_id,
            'delivery_date_id' => $this->Box->delivery_date_id
        ));
        if ($CustDeliveryDate)
            return $CustDeliveryDate->delivery_address;
        else
            return 'No location set!';
    }

    public function getQrCode()
    {
        $base = Yii::getPathOfAlias('webroot');
        $urlPath = '/images/user_boxes/qr/' . $this->user_box_id . '.png';
        $filePath = $base . $urlPath;

        $url = 'http://' . Yii::app()->request->serverName;
        $url.=Yii::app()->createUrl('customerBox/setDelivered', array('id' => $this->user_box_id));

        Yii::import('boxomatic.extensions.qrcode.QRCode');
        $code = new QRCode($url);
        $code->create($filePath);

views/customerBox/_form.php
<?php
	Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl . '/js/customerbox/_form.js',CClientScript::POS_END);
?>
<div class="form">
<?php $form=$this->beginWidget('application.widgets.SnapActiveForm', array(
	'id'=>'customer-box-form',
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<?php $this->widget('bootstrap.widgets.BsGridView', array(
		'id'=>'box-sizes-grid',
		'dataProvider'=>$Boxes->search(),
		'filter'=>$Boxes,
		'summaryText'=>'',
		'selectionChanged'=>'selectBox',
		'enablePagination'=>false,
		'enableSorting'=>false,
		'columns'=>array(
			array(
				'name'=>'size_id',
				'value'=>'$data->BoxSize->box_size_name',
				'filter'=>CHtml::listData(BoxSize::model()->findAll(), 'id', 'box_size_name'),
			),
			array(
				'name'=>'box_price',
				'filter'=>CHtml::listData(Boxes::model()->findAll(array('order'=>'box_price')), 'box_price', 'box_price'),
			),
			array(
				'name'=>'delivery_date_id',
				'value'=>'Yii::app()->dateFormatter->format("EEE, MMM d",$data->DeliveryDate->date)',
				'filter'=>CHtml::listData(DeliveryDate::model()->findAll(array('order'=>'date')), 'id', 'date'),
			)
		),
	)); ?>
	
	<div class="row quantity">
		<?php echo $form->labelEx($model,'quantity'); ?>
		<?php echo $form->textField($model,'quantity',array('class'=>'number')); ?>
		<?php echo $form->error($model,'quantity'); ?>
	</div>
	
	<div id="selected-box">
		<?php if($SelectedBox): ?>
		<div class="half">
			<h2>Items in box</h2>
			<?php if($items): ?>
				<?php 
				$this->widget('zii.widgets.CListView', array(
					'summaryText'=>'',
					'enablePagination'=>false,
					'enableSorting'=>false,
					'dataProvider'=>$items,
					'itemView'=>'../boxItem/_view',
				));
				?>
			<?php endif; ?>
		</div>

		<div class="half padLeft">
			<h2>Order Information</h2>
			<?php echo $form->hiddenField($model,'box_id'); ?>

			<?php $Location=$model->Customer->Location; ?>

			<div class="info">
				<div class="row">
					<span class="label"><?php echo $Location->getAttributeLabel('location_name') ?></span>
					<span class="value"><?php echo $Location->location_name; ?></span>
				</div>
				<div class="row">
					<span class="label"><?php echo $model->quantity ?> x <?php echo $SelectedBox->BoxSize->box_size_name; ?> Box</span>
					<span class="value number"><?php echo $model->total_box_price; ?></span>
				</div>
				
				<?php if((int)$model->total_delivery_price): //only show delivery cost if its greater than 0 ?>
				<div class="row">
					<span class="label"><?php echo $model->quantity ?> x <?php echo $Location->getAttributeLabel('location_delivery_value') ?></span>
					<span class="value number"><?php echo $model->total_delivery_price; ?></span>
				</div>
				<?php endif; ?>
				
				<div class="row total">
					<span class="label"><?php echo $model->getAttributeLabel('total_price') ?></span>
					<span class="value number"><?php echo $model->total_price; ?></span>
				</div>
			</div>
			<div class="row buttons">
				<?php echo CHtml::submitButton($model->isNewRecord ? 'Place order' : 'Update order'); ?>
			</div>

		</div>
	<?php endif; ?>
	</div>
	

<?php $this->endWidget(); ?>

</div><!-- form -->

views/customerBox/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('application.widgets.SnapActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'user_box_id'); ?>
		<?php echo $form->textField($model,'user_box_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_id'); ?>
		<?php echo $form->textField($model,'user_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'box_id'); ?>
		<?php echo $form->textField($model,'box_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'quantity'); ?>
		<?php echo $form->textField($model,'quantity'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

views/customerBox/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_box_id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->user_box_id), array('view', 'id'=>$data->user_box_id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo CHtml::encode($data->user_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('box_id')); ?>:</b>
	<?php echo CHtml::encode($data->box_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('quantity')); ?>:</b>
	<?php echo CHtml::encode($data->quantity); ?>
	<br />


</div>

views/customerBox/admin.php
<?php
$this->menu=array(
	array('label'=>'List UserBox', 'url'=>array('index')),
	array('label'=>'Create UserBox', 'url'=>array('create')),
);
?>

<h1>Manage Customer Boxes</h1>

<?php 

$this->widget('bootstrap.widgets.BsGridView', array(
	'id'=>'customer-box-grid',
	'dataProvider'=>$model->search(),
//	'filter'=>$model,
	'columns'=>array(
		array(
			'class'=>'CLinkColumn',
			'header'=>User::model()->getAttributeLabel('first_name'),
			'labelExpression'=>'$data->Customer->User->first_name',
			'urlExpression'=>'Yii::app()->createUrl("user/view",array("id"=>$data->Customer->User->id))',
			'visible'=>Yii::app()->user->checkAccess("admin"),
		),
		'Box.BoxSize.box_size_name',
		'quantity',
		'total_price',
		array(
			'name'=>'Box.delivery_date_id',
			'value'=>'Yii::app()->dateFormatter->format("EEE, MMM d",$data->Box->DeliveryDate->date)',
		),
		array(
			'class'=>'bootstrap.widgets.BsButtonColumn',
		),
	),
)); 

?>

views/customerBox/create.php
<?php
$this->menu=array(
	array('label'=>'List UserBox', 'url'=>array('index')),
	array('label'=>'Manage UserBox', 'url'=>array('admin')),
);
?>

<h1>Order a Box</h1>

<?php echo $this->renderPartial('_form', array(
	'model'=>$model,
	'Boxes'=>$Boxes,
	'items'=>$items,
	'SelectedBox'=>$SelectedBox)); 
?>

views/customerBox/index.php
<?php
$this->menu=array(
	array('label'=>'Create UserBox', 'url'=>array('create')),
	array('label'=>'Manage UserBox', 'url'=>array('admin')),
);
?>

<h1>Customer Boxes</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

views/customerBox/order.php
<?php
	/*$$cs=Yii::app()->clientScript;*/
	$cs=Yii::app()->clientScript;
	$cs->registerScriptFile(Yii::app()->request->baseUrl . '/js/pages/customBox/order.js', CClientScript::POS_END);
?>
<script type="text/javascript">
	var locCosts = <?php echo json_encode(CHtml::listData(Location::model()->findAll(),'location_id','location_delivery_value')) ?>;
</script>

<div class="row">
	<div class="large-8 columns">
		<h2>Order Summary</h2>

		<div class="section-container auto" data-section>
			<section>
				<p class="title" data-section-title><a href="#panel1">Orders</a></p>
				<div class="content" data-section-content>
					<div class="row">
						<div class="large-12 columns">
							<?php
								if(isset($_GET['all']))
									echo CHtml::link('View current orders', array('order','#'=>'orders'), array('class' => 'button small'));
								else
									echo CHtml::link('View all orders',array('order','all'=>'true','#'=>'orders'), array('class' => 'button small'));	
							?>
						</div>
						<?php 

						$form=$this->beginWidget('application.widgets.SnapActiveForm', array(
							'id'=>'customer-order-form', 
							// 'htmlOptions' => array('class' => 'custom'), 	
							'enableAjaxValidation'=>false,
						)); 

						echo CHtml::hiddenField('box_size_count', count($BoxSizes));

						foreach($BoxSizes as $BoxSize){
							echo CHtml::hiddenField('box_size_label_' . $BoxSize->id, $BoxSize->box_size_name, array('class'=>'boxSizeLabel'));
						}

						?>
						<div class="large-12 columns">
							<ul class="no-bullet">
								
								<?php $runningBalance=$Customer->balance; ?>
								
								<?php foreach($DeliveryDates as $DeliveryDate): ?>

								<?php

									$UserBox=null;
									$disabled='';
									$classes='';

									if(strtotime($DeliveryDate->date) < $deadline && !Yii::app()->user->shadow_id || $DeliveryDate->disabled) {
										$disabled='disabled';
										$classes.=' pastDeadline';
									} else {
										//only subtract the running balance if it hasn't already been subtracted from their credit (i.e. past the deadline)
										$runningBalance-=$Customer->totalByDeliveryDate($DeliveryDate->id);
									}

									if($runningBalance >= 0) {
										$classes.=' enoughCredit';
									} else if ($runningBalance < 0  && time() > strtotime('-14 days', strtotime($DeliveryDate->date))) {
										$classes.=' insufficientCredit';
									}

								?>

								<li class="<?php echo $classes; ?>">
									<div class="row">
										<div class="large-4 columns">
											<p><?php echo SnapFormat::dayOfYear($DeliveryDate->date) ?></p>
											<?php 
												$Order=Order::model()->findByAttributes(array('delivery_date_id'=>$DeliveryDate->id, 'user_id'=>Yii::app()->user->user_id));
												if(!$Order) {
													$Order=new Order;
													$Order->delivery_date_id=$DeliveryDate->id;
													$Order->user_id=Yii::app()->user->user_id;
													$Order->location_id=$Customer->Location->location_id;
													$Order->save();
												}
												echo CHtml::hiddenField('delivery_price_'.$Order->id, $Order->Location->location_delivery_value);
											?>
										</div>

										<div class="large-8 columns">
											<?php
												$attribs=array('class'=>'deliverySelect');
												if($disabled)
													$attribs+=array('disabled'=>'disabled');
												echo CHtml::dropDownList('CustDeliveryDates[' . $Order->id . ']', $Order->location_key, $Order->Customer->getDeliveryLocations(),$attribs); 
											?>
										</div>
									</div>

									<div class="row">
										<div class="large-6 columns">
											<?php 

											foreach($DeliveryDate->MergedBoxes as $Box):

											$UserBox=UserBox::findUserBox($DeliveryDate->id, $Box->size_id, Yii::app()->user->user_id);
											$quantity=$UserBox ? $UserBox->quantity : 0;

											$attribs = array('min'=>'0');
											if($disabled)
												$attribs += array('disabled'=>'disabled');
											else
												$attribs += array('class' => 'numeric'); 
											?>
											
											<?php if($Box->BoxSize->box_size_name): ?>

												<div class="large-4 columns">
													<label for=""><?php echo $Box->BoxSize->box_size_name; ?></label>
													<!-- <input type="text" class="<?php if(!$disabled): ?>numeric<?php endif; ?>" name="Orders[<?php echo $Box->box_id; ?>]" <?php if($disabled): ?>disabled<?php endif; ?>> -->
													<!-- <input id="b_value_<?php echo $Box->size_id; ?>" type="hidden" class="box_value" name="box_value" value="<?php echo $Box->box_price; ?>"> -->
													<?php echo CHtml::textField('Orders[' . $Box->box_id . ']', $quantity, $attribs); ?>
													<?php echo CHtml::hiddenField('box_value', $Box->box_price,  array('id'=>'b_value_' . $Box->size_id)); ?>	
												</div>
											
											<?php endif; ?>

											<?php endforeach; ?>

										</div>

										<div class="large-6 columns">
											<table>
												<thead>
													<tr>
														<th>Boxes</th>
														<th>Extras</th>
														<th>Delivery</th>
														<th>Total</th>
													</tr>
												</thead>
												<tbody>
													<tr>
														<td class='boxes'><?php echo SnapFormat::currency($Customer->totalBoxesByDeliveryDate($DeliveryDate->id)) ?></td>
														<td class='extras'>?</td>
														<td class='delivery'><?php echo SnapFormat::currency($Customer->totalDeliveryByDeliveryDate($DeliveryDate->id)); ?></td>
														<td class='total'>
															<strong><?php echo SnapFormat::currency($Customer->totalByDeliveryDate($DeliveryDate->id)) ?></strong>
															<?php if(Yii::app()->user->shadow_id): ?>
															<?php echo CHtml::link('update',array('deliveryDate/updateUserBoxes','date_id'=>$DeliveryDate->id,'cust_id'=>$Customer->user_id), array('class' => 'button small')); ?>
															<?php endif; ?>
														</td>
													</tr>
												</tbody>
											</table>
										</div>
										
										<div class="large-12 columns">
											<?php echo CHtml::link('Update Extras',array('OrderItem/order','date'=>$DeliveryDate->id),array('class'=>'button small')) ?>
										</div>
										
									</div>
								</li>
								<?php endforeach; ?>
							</ul>

						</div>
						<div class="large-12 columns">
							<div class="large-6 columns">
								<?php echo CHtml::link('Load more dates',array('order','show'=>$show+4,'#'=>'orders'), array('class' => 'button')); ?>
							</div>
							<div class="large-6 columns">
								<div class="right">
									<?php echo CHtml::submitButton('Update Orders', array('class' => 'button')); ?>
								</div>
							</div>
						</div>

						<?php $this->endWidget(); ?>

					</div>

					
				</div>
			</section>
			<section>
				<p class="title" data-section-title><a href="#panel2">Order in Advance</a></p>
				<div class="content" data-section-content>

					<h6 class='mb'>This will reset your orders for the selected amount of time to the setting chosen here. Press the "Clear all orders" button to start over.</h6>

					<?php $form=$this->beginWidget('application.widgets.SnapActiveForm', array(
					'id'=>'reccuring-customer-order-form', 
					// 'htmlOptions' => array('class' => 'custom'), 
					'enableAjaxValidation'=>false,
					)); ?>

					
					<?php 
						echo CHtml::label('Deliver to', 'delivery_price_');
						echo $form->dropDownList($Customer,'delivery_location_key',$Customer->getDeliveryLocations(),array('class'=>'deliverySelect')); 
					?>
					
					<?php echo CHtml::link('Add new delivery location',array('customerLocation/create','custId'=>$Customer->user_id,'order'=>1), array('class' => 'button small'))?>
					
					<?php echo CHtml::hiddenField('delivery_price_', $Customer->Location->location_delivery_value); ?>

					<table style='width:100%;'>
						<thead>
							<tr>
								<th style='width:35%'>Sizes</th>
								<th>Boxes</th>
								<th>Delivery</th>
								<th>Total</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									<div class="row">
										<?php foreach($BoxSizes as $boxsize): ?>
										<?php if($boxsize->box_size_name != ''): ?>
										<div class="large-4 columns">
											<label for=""><?php echo $boxsize->box_size_name; ?></label>
											<?php echo CHtml::textField('Recurring[bs_' . $boxsize->id . ']','0',array('class'=>'number numeric','min'=>0)); ?>
											<?php echo $form->hiddenField($boxsize,'box_size_price', array('id'=>'bs_value_' . $boxsize->id)); ?>	
										</div>
										<?php endif; ?>
										<?php endforeach; ?>
									</div>
								</td>
								<td class='box'>$0.00</td>
								<td>$0.00</td>
								<td class='total'><strong>$0.00</strong></td>
							</tr>
						</tbody>
					</table>

					<div class="row">
						<div class="large-4 columns">
							<?php echo CHtml::label('Order in advance for', 'months_advance');  ?>
							<?php echo CHtml::dropDownList('months_advance',1,array(1=>'1 Month',3=>'3 Months',6=>'6 Months'));  ?>
						</div>
						<div class="large-4 columns">
							<?php echo CHtml::label('Starting from', 'starting_from');  ?>
							<?php echo CHtml::dropDownList('starting_from',1,DeliveryDate::getFutureDeliveryDates());  ?>
							
						</div>
						<div class="large-4 columns">
							<?php echo CHtml::label('Every', 'every');  ?>
							<?php echo CHtml::dropDownList('every',1,array('week'=>'week','fortnight'=>'fortnight'));  ?>
						</div>
					</div>

					<div class="row">
						<div class="large-12 columns">
							<div class="right">
								<?php echo CHtml::submitButton('Set recurring order', array('name'=>'btn_recurring','class'=>'button')); ?>
							</div>
						</div>
					</div>

					<?php $this->endWidget(); ?>

				</div>
			</section>
		</div>
	</div>
	<div class="large-4 columns">
		<h2>Transactions</h2>
		<?php $this->widget('zii.widgets.CListView', array(
			'dataProvider'=>new CActiveDataProvider('UserPayment',array(
				'criteria'=>array(
					'condition'=>'user_id='.$Customer->user_id,
					'order'=>'payment_date DESC',
					'limit'=>5,
				),
				'pagination'=>false,
			)),
			'itemView'=>'../customerPayment/_view',
			'summaryText'=>false,
		)); ?>
	</div>
</div>

views/customerBox/set_delivered.php
<p>Box set to Collected/Delivered</p>

views/customerBox/update.php
<?php
$this->menu=array(
	array('label'=>'List UserBox', 'url'=>array('index')),
	array('label'=>'Create UserBox', 'url'=>array('create')),
	array('label'=>'View UserBox', 'url'=>array('view', 'id'=>$model->user_box_id)),
	array('label'=>'Manage UserBox', 'url'=>array('admin')),
);
?>

<h1>Update Order</h1>

<?php echo $this->renderPartial('_form', array(
	'model'=>$model,
	'Boxes'=>$Boxes,
	'items'=>$items,
	'SelectedBox'=>$SelectedBox)); 
?>

views/customerBox/view.php
<?php
$this->menu=array(
	array('label'=>'List UserBox', 'url'=>array('index')),
	array('label'=>'Create UserBox', 'url'=>array('create')),
	array('label'=>'Update UserBox', 'url'=>array('update', 'id'=>$model->user_box_id)),
	array('label'=>'Delete UserBox', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->user_box_id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage UserBox', 'url'=>array('admin')),
);
?>

<h1>View Box</h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'Customer.User.full_name',
		'Box.BoxSize.box_size_name',
		'Box.box_price',
		'Box.DeliveryDate.date',
		'quantity',
		'total_price',
	),
)); ?>

<h2>Items</h2>

<?php 
$this->widget('zii.widgets.CListView', array(
	'summaryText'=>'',
	'enablePagination'=>false,
	'enableSorting'=>false,
    'dataProvider'=>$items,
    'itemView'=>'../boxItem/_view',
));
?>