models/Supplier.php
<?php

/**
 * This is the model class for table "suppliers".
 *
 * The followings are the available columns in table 'suppliers':
 * @property integer $id
 * @property string $name
 * @property string $mobile
 * @property string $phone
 * @property string $address
 * @property string $address2
 * @property string $suburb
 * @property string $state
 * @property string $postcode
 * @property string $distance_kms
 * @property string $bank_account_name
 * @property string $bank_bsb
 * @property string $bank_acc
 * @property string $email
 * @property string $website
 * @property string $certification_status
 * @property string $order_days
 * @property string $produce
 * @property string $notes
 * @property string $payment_details
 * @property string $profile
 * @property string $image
 *
 * The followings are the available model relations:
 * @property SupplierProducts[] $supplierProducts
 */
class Supplier extends BoxomaticActiveRecord
{
	const STATUS_DELETED=0;
	const STATUS_ACTIVE=1;
	
	public $item_search;
	public $supplier_products;
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Supplier the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return $this->tablePrefix . 'suppliers';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('longitude, lattitude', 'numerical'),
			array('company_name, Ordering, ABN, name, mobile, address2, suburb, postcode, distance_kms, bank_account_name, bank_bsb, bank_acc', 'length', 'max'=>45),
			array('phone, address, website, certification_status', 'length', 'max'=>150),
			array('state', 'length', 'max'=>50),
			array('email', 'length', 'max'=>100),
            array('image', 'file', 'types' => 'jpg, gif, png', 'allowEmpty' => true),
			array('order_days, certification_status, website, order_days', 'length', 'max'=>255),
			array('produce, notes, payment_details, profile', 'length', 'max'=>500),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('item_search, id, name, mobile, phone, address, address2, suburb, state, postcode, distance_kms, bank_account_name, bank_bsb, bank_acc, email, website, certification_status, order_days, produce, notes, payment_details, profile', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'SupplierProducts' => array(self::HAS_MANY, 'SupplierProduct', 'id'),
			'BoxItems' => array(self::HAS_MANY , 'BoxItem', 'box_item_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Supplier',
			'name' => 'Supplier Name',
			'mobile' => 'Mobile',
			'phone' => 'Phone',
			'company_name' => 'Company Name',
			'address' => 'Street Address',
			'address2' => '',
			'suburb' => 'Suburb',
			'state' => 'State',
			'postcode' => 'Postcode',
			'distance_kms' => 'Distance(km)',
			'bank_account_name' => 'Bank Account Name',
			'bank_bsb' => 'Bank BSB',
			'bank_acc' => 'Bank Acc',
			'email' => 'Email',
			'website' => 'Website',
			'certification_status' => 'Certification Status',
			'order_days' => 'Order Days',
			'produce' => 'Produce',
			'notes' => 'Notes',
			'payment_details' => 'Payment Details',
			'item_search' => 'Produce',
			'lattitude' => 'Latitude',
			'longitude' => 'Longitude',
			'ABN'=>'ABN',
            'profile' => 'Profile',
            'image' => 'Supplier Image'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{	
		$pageSize=isset($_GET['pageSize'])?$_GET['pageSize']:50;
		Yii::app()->user->setState('pageSize',$pageSize);
		$criteria=new CDbCriteria;
		//$criteria->with=array('SupplierProducts');
		$tablePrefix=SnapUtil::config('boxomatic/tablePrefix');
		$criteria->select='t.*, GROUP_CONCAT(SupplierProducts.name SEPARATOR ", ") as supplier_products';
		$criteria->join="LEFT JOIN {$tablePrefix}supplier_products SupplierProducts ON SupplierProducts.supplier_id = t.id";
		$criteria->group='t.id';
		
		if(!empty($this->item_search)) 
		{
			$searchItems=explode(',',$this->item_search);
			
			foreach($searchItems as $searchItem) {
				$criteria->addCondition('SupplierProducts.name LIKE "%' . $searchItem . '%"','OR');
			}
		}
		$criteria->compare('t.id',$this->id);
		$criteria->compare('t.name',$this->name,true);
		$criteria->compare('t.mobile',$this->mobile,true);
		$criteria->compare('t.phone',$this->phone,true);
		$criteria->compare('address',$this->address,true);
		$criteria->compare('address2',$this->address2,true);
		$criteria->compare('suburb',$this->suburb,true);
		$criteria->compare('state',$this->state,true);
		$criteria->compare('postcode',$this->postcode,true);
		$criteria->compare('distance_kms',$this->distance_kms,true);
		$criteria->compare('bank_account_name',$this->bank_account_name,true);
		$criteria->compare('bank_bsb',$this->bank_bsb,true);
		$criteria->compare('bank_acc',$this->bank_acc,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('website',$this->website,true);
		$criteria->compare('certification_status',$this->certification_status,true);
		$criteria->compare('order_days',$this->order_days,true);
		$criteria->compare('produce',$this->produce,true);
		$criteria->compare('notes',$this->notes,true);
		$criteria->compare('payment_details',$this->payment_details,true);
        $criteria->compare('profile', $this->profile, true);

		$criteria->addCondition('status='.self::STATUS_ACTIVE);
		
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=> array(
                'pageSize' => $pageSize
            ),
		));
	}
	
	public static function getDropdownListItems()
	{
		$criteria = new CDbCriteria;
		$criteria->order = 'name';
		$criteria->addCondition('status='.self::STATUS_ACTIVE);	

		$items = self::model()->findAll($criteria);
		return CHtml::listData($items,'id','name');
	}
	
	public static function getOSDropdownListItems($supplierId=null)
	{
		$criteria = new CDbCriteria;
		$criteria->select = 'certification_status';
		$criteria->order = 'certification_status';
		$criteria->distinct = true;
		if($supplierId) {
			$criteria->addCondition('t.id='.$supplierId);	
		}
		
		$items = self::model()->findAll($criteria);
		return CHtml::listData($items,'certification_status','certification_status');
	}

    public function beforeSave()
    {
        $uploadFile = CUploadedFile::getInstance($this, 'image');
        if ($uploadFile)
            $this->image = $uploadFile;

        return parent::beforeSave();
    }

    public function afterSave()
    {
        parent::afterSave();

        $field = 'image';
        $dataDir = Yii::getPathOfAlias('frontend.data');

        $dirPath = $dataDir . '/' . strtolower(__CLASS__);
        if (!file_exists($dirPath)) {
            mkdir($dirPath, 0777, true);
        }

        if ($this->$field instanceof CUploadedFile && !$this->$field->saveAs($dirPath . '/' . $field . '_' . $this->id)) {
            Yii::app()->user->setFlash('danger', 'problem saving image for field: ' . $field);
        }

        //Delete Cache
        $shortSrc = md5('/' . strtolower(__CLASS__) . '/' . $field . '_' . $this->id);
        $cachePath = Yii::getPathOfAlias('web') . '/cache/';

        $files = new DirectoryIterator($cachePath);
        $filesFiltered = new RegexIterator($files, sprintf('(^%s.*$)i', preg_quote($shortSrc)));
        foreach ($filesFiltered as $file) {
            unlink($file->getPathname());
        }

        $this->refresh(); //reload the uploaded attribute
    }
}

controllers/SupplierController.php
<?php

class SupplierController extends BoxomaticController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','GeoCode'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','map','search'),
				'roles'=>array('supplier'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','getListItems','create','update','map','search','export'),
				'roles'=>array('Admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Supplier;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Supplier']))
		{
			$model->attributes=$_POST['Supplier'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->layout='//layouts/column1';
		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Supplier']))
		{
            $oldImage = $model->image;
            $model->attributes=$_POST['Supplier'];

            $deleteImage = isset($_POST['image_delete']) ? $_POST['image_delete'] : false;

			if($model->validate())
            {
                if ($deleteImage)
                    $model->image = null;
                else
                    $model->image = $oldImage;
                $model->save(false);

                $this->redirect(array('admin'));
            }
		}

		$this->layout='//layouts/column1';
		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$model=$this->loadModel($id);
			$model->status=0;
			$model->save();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Supplier');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
	
	/**
	 * Shows the supplier map
	 */
	public function actionMap()
	{
		$model=new Supplier('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Supplier']))
			$model->attributes=$_GET['Supplier'];

		$criteria=new CDbCriteria();
		$criteria->select='id,name,lattitude,longitude';
		
//		$Suppliers=$model->findAll($criteria);
		$Suppliers=$model->search(false)->getData();
		
		//Build supplier array and supplier items in a format suitable for Mustache js
		$supplierArray=SnapUtil::makeArray($Suppliers);
		foreach($Suppliers as $Supplier) {
			$supplierItems=SnapUtil::makeArray($Supplier->SupplierProducts);
			foreach($supplierItems as $gi) {
				$supplierArray[$Supplier->id]['SupplierProducts'][]=$gi;
			}
			$supplierArray[$Supplier->id]['has_items']=!empty($supplierArray[$Supplier->id]['SupplierProducts']) ? true : false;
		}

		$this->layout='//layouts/column1';
		$this->render('map',array(
			'model'=>$model,
			'Suppliers'=>$supplierArray,
		));
	}
	
	public function actionSearch()
	{
		$model=new Supplier('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Supplier']))
			$model->attributes=$_GET['Supplier'];

		$criteria=new CDbCriteria();
		$criteria->select='id,name,lattitude,longitude';

		$Suppliers=$model->search(false)->getData();
		
		//Build supplier array and supplier items in a format suitable for Mustache js
		$supplierArray=SnapUtil::makeArray($Suppliers);
		foreach($Suppliers as $Supplier) {
			$supplierItems=SnapUtil::makeArray($Supplier->SupplierProducts);
			foreach($supplierItems as $gi) {
				$supplierArray[$Supplier->id]['SupplierProducts'][]=$gi;
			}
			$supplierArray[$Supplier->id]['has_items']=!empty($supplierArray[$Supplier->id]['SupplierProducts']) ? true : false;
		}
		
		echo json_encode($supplierArray);
		
		exit;
	}
	
	public function actionGetListItems($supplierId=null)
	{
		$items = SupplierProduct::getDropdownListItems($supplierId);
		echo json_encode($items);
		exit;
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Supplier('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Supplier']))
			$model->attributes=$_GET['Supplier'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	/**
	 * Csv Export
	 */
	public function actionExport()
	{
		  CsvExport::export(
				Supplier::model()->findAll(), // a CActiveRecord array OR any CModel array
				array(
					'id' => array('number'), 
					'name' => array('text'),
					'company_name' => array('text'),
					'Ordering' => array('text'),
					'email' => array('text'),
					'website' => array('text'),
					'phone' => array('text'),
					'mobile' => array('text'), 
					'address' => array('text'), 
					'address2' => array('text'), 
					'postcode' => array('text'), 
					'suburb' => array('text'), 
					'state' => array('text'),
					'distance_kms' => array('text'), 
					'ABN' => array('text'),
					'bank_account_name' => array('text'),
					'bank_bsb' => array('text'),
					'bank_acc' => array('text'),
					'certification_status' => array('text'),
					'order_days' => array('text'), 
					'produce' => array('text'), 
					'notes' => array('text'),
					'payment_details' => array('text'),
					'lattitude' => array('number'), 
					'longitude' => array('number'), 
					'status' => array('number'), 
				), 
				true, // boolPrintRows
				'boxomatic-suppliers--'.date('Y-m-d').'.csv',
				','
		);
	}
	
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Supplier::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='supplier-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	public function actionGeoCode() 
	{		
		define("MAPS_HOST", "maps.google.com");
		//define("KEY", "AIzaSyAU7aJq2EcQYJV7BsjZg1lkhR2dYBTZxfU");
		define("KEY", "AIzaSyDtX7h4kdxUSrWpqVz3uRYP2-gxDMXa6hM");
		
		$delay = 0;
		$base_url = "http://" . MAPS_HOST . "/maps/geo?output=xml" . "&key=" . KEY;
		
		$Suppliers=Supplier::model()->findAll();
		
		foreach($Suppliers as $supplier)
		{ 
			$id = $supplier->id;
			$address = $supplier->address . ' ' . $supplier->address2 . ', ' . $supplier->suburb . ', ' . $supplier->state . ', ' . $supplier->postcode;
			$address = trim($address, ' ,');
		
			if(!empty($address))
			{
				$request_url = $base_url . "&q=" . urlencode($address . ', Australia');
				$xml = simplexml_load_file($request_url) or die("url not loading");
				$status = $xml->Response->Status->code;
				
				if (strcmp($status, "200") == 0) 
				{
					// Successful geocode
					$geocode_pending = false;
					$coordinates = $xml->Response->Placemark->Point->coordinates;
					$coordinatesSplit = split(",", $coordinates);
					// Format: Longitude, Latitude, Altitude
					$lat = $coordinatesSplit[1];
					$lng = $coordinatesSplit[0];
					
					$supplier->lattitude = $lat;
					$supplier->longitude = $lng;
					$supplier->save();
		
				} 
				else if (strcmp($status, "620") == 0) 
				{
					// sent geocodes too fast
					$delay += 100000;
				} 
				else 
				{
					// failure to geocode
					$geocode_pending = false;
					echo "Address " . $address . ", Australia failed to geocoded. ";
					echo "Received status " . $status . "\n";
				}
				usleep($delay);
			}
		}

	}
}

views/supplier/_form.php
<?php
/**
 * @var $this SupplierController
 * @var $form SnapActiveForm
 * @var $model Supplier
 */
?>
<div class="form">
<?php $form=$this->beginWidget('application.widgets.SnapActiveForm', array(
	'id'=>'supplier-form',
	'enableAjaxValidation'=>false,
	'layout' => BsHtml::FORM_LAYOUT_HORIZONTAL,
	'htmlOptions' => array('enctype' => 'multipart/form-data', 'class'=>'row'),
)); ?>

	<div class="col-lg-9 clearfix">
		<?php echo $form->textFieldControlGroup($model,'name'); ?>
		<?php echo $form->textFieldControlGroup($model,'company_name'); ?>
		<?php //echo $form->textFieldControlGroup($model,'Ordering'); ?>
		<?php echo $form->textFieldControlGroup($model,'email'); ?>
		<?php echo $form->textFieldControlGroup($model,'website'); ?>
		<?php echo $form->textFieldControlGroup($model,'phone'); ?>
		<?php echo $form->textFieldControlGroup($model,'mobile'); ?>
		<?php echo $form->textFieldControlGroup($model,'address'); ?>
		<?php echo $form->textFieldControlGroup($model,'suburb'); ?>
		<?php echo $form->textFieldControlGroup($model,'postcode'); ?>
		<?php echo $form->dropDownListControlGroup($model,'state',SnapUtil::config('boxomatic/states')); ?>
		<?php echo $form->textFieldControlGroup($model,'ABN'); ?>
		<?php echo $form->textFieldControlGroup($model,'distance_kms'); ?>
		<?php echo $form->textFieldControlGroup($model,'bank_account_name'); ?>
		<?php echo $form->textFieldControlGroup($model,'bank_bsb'); ?>
		<?php echo $form->textFieldControlGroup($model,'bank_acc'); ?>
		<?php echo $form->textFieldControlGroup($model,'certification_status'); ?>
		<?php echo $form->textFieldControlGroup($model,'order_days'); ?>
        <?php echo $form->imageField($model, 'image'); ?>
		<?php echo $form->textAreaControlGroup($model,'produce'); ?>
		<?php echo $form->textAreaControlGroup($model,'notes'); ?>
        <?php echo $form->textAreaControlGroup($model,'profile'); ?>
		<?php echo $form->textFieldControlGroup($model,'payment_details'); ?>
		<?php echo $form->textFieldControlGroup($model,'lattitude'); ?>
		<?php echo $form->textFieldControlGroup($model,'longitude'); ?>
	</div>

	<?php echo $this->renderPartial('//layouts/_form_sidebar'); ?>

<?php $this->endWidget(); ?>
</div>

views/supplier/_search.php
<?php $form=$this->beginWidget('application.widgets.SnapActiveForm', array(
	'id'=>'supplier-search',
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
	'layout' => BsHtml::FORM_LAYOUT_HORIZONTAL,
	'htmlOptions' => array('class'=>'row'),
)); ?>
	<div class="col-lg-9 clearfix">
		<?php echo $form->textFieldControlGroup($model,'name'); ?>
		<?php echo $form->textFieldControlGroup($model,'item_search'); ?>
		
		<button class="btn btn-primary pull-right" name="yt0" type="submit">
			<span class="glyphicon glyphicon-search"></span> Search
		</button>
		
	</div>
<?php $this->endWidget(); ?>

views/supplier/_view.php
<div class="large-6 columns">
	<div class="panel">
		<ul class='no-bullet'>
			<li><?php echo CHtml::encode($data->getAttributeLabel('id')); ?> : <?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?></li>
			<li><?php echo CHtml::encode($data->getAttributeLabel('website')); ?> : <?php echo CHtml::encode($data->website); ?></li>
			<li><?php echo CHtml::encode($data->getAttributeLabel('distance_kms')); ?> : <?php echo CHtml::encode($data->distance_kms); ?></li>
			<li><?php echo CHtml::encode($data->getAttributeLabel('bank_account_name')); ?> : <?php echo CHtml::encode($data->bank_account_name); ?></li>
			<li><?php echo CHtml::encode($data->getAttributeLabel('bank_bsb')); ?> : <?php echo CHtml::encode($data->bank_bsb); ?></li>
			<li><?php echo CHtml::encode($data->getAttributeLabel('bank_acc')); ?> : <?php echo CHtml::encode($data->bank_acc); ?></li>
			<li><?php echo CHtml::encode($data->getAttributeLabel('certification_status')); ?> : <?php echo CHtml::encode($data->certification_status); ?></li>
		</ul>
	</div>
</div>
<?php /*
<b><?php echo CHtml::encode($data->getAttributeLabel('order_days')); ?>:</b>
<?php echo CHtml::encode($data->order_days); ?>
<br />

<b><?php echo CHtml::encode($data->getAttributeLabel('produce')); ?>:</b>
<?php echo CHtml::encode($data->produce); ?>
<br />

<b><?php echo CHtml::encode($data->getAttributeLabel('notes')); ?>:</b>
<?php echo CHtml::encode($data->notes); ?>
<br />

<b><?php echo CHtml::encode($data->getAttributeLabel('payment_details')); ?>:</b>
<?php echo CHtml::encode($data->payment_details); ?>
<br />

*/ ?>

views/supplier/admin.php
<?php
$this->breadcrumbs=array(
	'Box-O-Matic'=>array('/snapcms/boxomatic/index'),
	'Suppliers',
);
$this->menu=array(
	array('icon' => 'glyphicon glyphicon-plus-sign', 'label'=>'Create Supplier', 'url'=>array('create')),
	array('icon' => 'glyphicon glyphicon-export', 'label'=>'Export Suppliers', 'url'=>array('export')),
);
$this->page_heading = 'Suppliers';
Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('supplier-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
Yii::app()->clientScript->registerScript('initPageSize',<<<EOD
    $('#content').on('change', '.change-pageSize', function() {
		$.fn.yiiGridView.update('supplier-grid',{ data:{ pageSize: $(this).val() }})
	});
EOD
,CClientScript::POS_READY);
?>
	<div class="large-12 columns search-form" style="display:none">
		<?php $this->renderPartial('_search',array(
			'model'=>$model,
		)); ?>
	</div>

<?php
$this->beginWidget('bootstrap.widgets.BsPanel', array(
	'title'=>'&nbsp;',
));
?>
<?php $dataProvider=$model->search(); ?>
<?php $pageSize=Yii::app()->user->getState('pageSize',50); ?>
<?php $this->widget('bootstrap.widgets.BsGridView', array(
	'id'=>'supplier-grid',
	'dataProvider'=>$dataProvider,
	'cssFile' => '', 
	'filter'=>$model,
	'summaryText'=>'Displaying {start}-{end} of {count} result(s). ' .
		CHtml::dropDownList(
			'pageSize',
			$pageSize,
			array(5=>5,10=>10,20=>20,50=>50,100=>100),
			array('class'=>'change-pageSize')) .
		' rows per page',
	'columns'=>array(
		'id',
		'name',
		'mobile',
		'phone',
		//'address',
		array(
			'name'=>'item_search',
			'value'=>'$data->supplier_products'
		),
		array(
			'class'=>'bootstrap.widgets.BsButtonColumn',
            'template' => '{update}{delete}{purchase}',
            'buttons' => array(
                'purchase' => array(
                    'url' => 'array("supplierPurchase/create","supplier"=>$data->id)',
                    'label'=>'<i class="glyphicon glyphicon glyphicon-list-alt"></i>',
                    'options'=>array('title'=>'Create Purchase'),
                ),
            )
		),
	),
)); ?>
<?php $this->endWidget(); ?>

views/supplier/index.php
<?php
$this->menu=array(
	array('label'=>'Create Supplier', 'url'=>array('create')),
	array('label'=>'Manage Supplier', 'url'=>array('admin')),
);
?>

<div class="row">
	<div class="large-12 columns">
		<h1>Suppliers</h1>
	</div>
	<?php $this->widget('zii.widgets.CListView', array(
		'dataProvider'=>$dataProvider,
		'itemView'=>'_view',
	)); ?>
	
</div>

views/supplier/view.php
<div class="row">
	<div class="large-12 columns">
		<h1><?php echo $model->name; ?></h1>
	</div>
	<div class="large-12 columns">
		<div class="panel">
			<?php echo CHtml::link('Create',array('supplier/create'), array('class' => 'button small')); ?>
			<?php echo CHtml::link('Update',array('supplier/update', 'id' => $model->id), array('class' => 'button small')); ?>
			<?php echo CHtml::link('Delete',array('supplier/delete', 'id' => $model->id), array('class' => 'button small')); ?>
			<?php echo CHtml::link('Manage',array('supplier/admin'), array('class' => 'button small')); ?>
		</div>
	</div>
	<div class="large-12 columns">
		<?php if(Yii::app()->user->checkAccess('Admin')): ?>

		<?php $this->widget('zii.widgets.CDetailView', array(
			'data'=>$model,
			'cssFile' => '',
			'attributes'=>array(
				'bank_account_name',
				'bank_bsb',
				'bank_acc',
				'certification_status',
				'order_days',
				'produce',
				'notes',
				'payment_details',
			),
		)); ?>

		<?php endif; ?>
	</div>
</div>